Personage
WildCodeSchool/2023-02-Orleans-Spe-P2-B pull request #4
Opened 2023-03-14 16:23 UTC by VioletaBD

2023-03-14 16:28 UTC, Alexis-Thibault requested changes

2023-03-14 16:28 UTC, Alexis-Thibault commented on assets/script/script.js
> +    console.log(cursors)
a supprimer

2023-03-14 16:28 UTC, Alexis-Thibault commented on index.html
> +  <div class="game">
supprimer div

2023-03-14 16:29 UTC, Alexis-Thibault approved these changes

2023-03-15 08:21 UTC, YDrogen requested changes

2023-03-15 08:21 UTC, YDrogen commented on assets/script/script.js
> +let game = new Phaser.Game(config)
C'est une `const` game n'est jamais réassigné

2023-03-15 08:21 UTC, YDrogen commented on index.html
> +  <link rel="stylesheet" href="/assets/style/style.css">
Il faut un chemin relatif `./`

2023-03-15 08:39 UTC, Alexis-Thibault approved these changes

2023-03-15 08:53 UTC, YDrogen approved these changes

2023-03-15 08:53 UTC, merged